[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hanzi-ocr"
version = "0.0.3"

dependencies = [
    "numpy",
    "torchvision",
    "torch",
    "pandas",
    "pillow",
    "scipy",
    "fonttools",
    "datasets",
    "opencc",
    "albumentations>=1.4.18",
    "torchmetrics>=1.5.2",
    "scikit-image>=0.26.0",
    "opencv-python>=5.0.0.93",
]

requires-python = ">= 3.12"
description = "An OCR project for Chinese characters (Hanzi)"
readme = "README.md"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.7.5",
]
