from PIL import Image, ImageDraw, ImageFont
import os, shutil
import argparse
from hanzi_ocr import utils
import pandas as pd
from fontTools.ttLib import TTFont

root_ = utils.find_project_root()



def delete_images(opts):
    """
    If requested by the user, deletes all the hanzi images previously generated

    Parameters
    -----------
    opts: argparse.Namespace
        Parameters given by the user
    """
    # Source - https://stackoverflow.com/a/185941
    # Posted by Nick Stinemates, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-07-08, License - CC BY-SA 4.0
    if opts.delete_previous_images:
        folder = os.path.join(root_, opts.data_folder, opts.save_location)
        if not os.path.exists(folder):
            os.makedirs(folder)
        for filename in os.listdir(folder):
            file_path = os.path.join(folder, filename)
            try:
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)
                elif os.path.isdir(file_path):
                    shutil.rmtree(file_path)
            except Exception as e:
                print("Failed to delete %s. Reason: %s" % (file_path, e))


def get_fonts_list(opts) -> list[str]:
    """
    Returns the files stored in the fonts directory, that is, returns a list of all the fonts to be rendered

    Parameters
    ----------
    opts: argparse.Namespace
        Parameters given by the user

    Returns
    ----------
    List of fonts stored in specified directory
    """
    return os.listdir(os.path.join(root_, opts.data_folder, opts.font_location))


def get_hanzi_list(opts) -> pd.DataFrame:
    """
    Reads the csv in which the hanzis are stored and returns the dataframe

    Parameters
    ----------
    opts: argparse.Namespace
        Parameters given by the user

    Returns
    ---------
    Pandas dataframe with the hanzi data
    """
    hanzi_df = pd.read_csv(
        os.path.join(root_, opts.data_folder, opts.hanzi_location, opts.hanzi_file_name)
    )
    return hanzi_df

def audit_font(font_location, hanzi_df, audit_traditional) -> dict:
    """
    Tells the program which characters are able to be rendered by a 
    particular font, those that aren't will be skipped so as to not 
    generate something useless or even harmful for training

    Parameters
    ---------
    font_location: str
        The location of the font to be loaded
    hanzi_df: pd.Dataframe
        Pandas DataFrame generated by the previous script (make_char_list.py)
    audit_traditional: bool
        Whether or not to check if traditional versions of the characters 
        are supported as well

    Returns
    ---------
        Dictionary with each character and whether it can be rendered 
        or not by the font being audited
    """
    supported = {}
    try:
        with TTFont(font_location) as font:
            cmap = font.getBestCmap()
            for r in hanzi_df.itertuples(index=True):
                # Despite being saved in different columns in the same row, 
                # traditional and simplified characters, if different, have
                # different code points, so we'll make sure to audit them 
                # separately if indicated
                if r.simplified != r.traditional:
                    if audit_traditional:
                        traditional_codepoint = ord(r.traditional)
                        supported[traditional_codepoint] = traditional_codepoint in cmap
                    
                    # we do not have to look up the codepoint for the simplified
                    # as we already have it in the codepoint column, which is the index
                    supported[r.codepoint] = r.Index in cmap
                # if the two characters are the same then we don't have to 
                # do anything special
                else:
                # Check if the code point exists in the cmap
                    supported[r.codepoint] = r.Index in cmap
    except Exception as e:
        print(f"Error loading font: {e}")
        return supported 
    
    return supported



def write_images(opts):
    """
    Generates the training images by loading each font stored locally,
    iterating through them one at a time, then for each font it iterates
    through each character stored in the character list, for each of these it
    generates an image using Pillow

    Parameters
    -----------
     opts: argparse.Namespace
        Parameters given by the user
    """
    # If it doesn't exist we create a folder for the fonts
    if not os.path.exists(os.path.join(root_, opts.data_folder, opts.font_location)):
        os.makedirs(os.path.join(root_, opts.data_folder, opts.font_location))
        print(
            f"WARNING: folder with fonts doesn't exist, creating folder, this will not generate images as there are no fonts to use"
        )

    # We want to generate a manifest to keep track of what character, font, size, etc is being generated on each file.
    manifest_df = pd.DataFrame(columns=["file name", "character", "font"])

    # If the specified folder for the generated images doesn't already exist we'll create it
    if not os.path.exists(os.path.join(root_, opts.data_folder, opts.save_location)):
        os.makedirs(os.path.join(root_, opts.data_folder, opts.save_location))

    # We'll get the list of saved fonts and iterate through them 
    fonts = get_fonts_list(opts)
    hanzi_df = get_hanzi_list(opts)
    num_img = 0
    # Weĺl load each font and iterate through our previously generated character list
    for font_name in fonts:
        try:
            font = ImageFont.truetype(
                font=os.path.join(root_, opts.data_folder, opts.font_location, font_name),
                size=opts.character_size,
            )
        except Exception as e:
            print(f"ERROR: Could not load {font_name}")
        for r in hanzi_df.itertuples(index=False):
        #for hanzi in ["影", "一", "口"]:
            # Some characters differ in their simplified and traditional forms, it this happens we'll save both if the save_traditional flag is True
            # Otherwise we'll keep only the simplified character
            if r.traditional != r.simplified:
                if opts.save_traditional:
                    img1 = Image.new("RGB", (opts.image_width, opts.image_height), "white")
                    draw1 = ImageDraw.Draw(img1)
                    # textbox_val = draw1.textbbox((opts.image_width/2, opts.image_height/2), text=r.traditional, font=font, anchor="mm", align="center")
                    # print(textbox_val)
                    file_name = f"hanzi_{r.codepoint}_{font_name}_trad.png"
                    draw1.text((opts.image_width/2, opts.image_height/2), text=r.traditional, font=font, fill="black", anchor="mm", align="center")
                    img1.save(
                        os.path.join(
                            root_,
                            opts.data_folder,
                            opts.save_location,
                            file_name,
                        )
                    )
                    manifest_df.loc[len(manifest_df)] = [file_name, r.traditional, font_name]
                    num_img += 1
                
                img2 = Image.new("RGB", (opts.image_width, opts.image_height), "white")
                draw2 = ImageDraw.Draw(img2)
                # textbox_val = draw2.textbbox((opts.image_width/2, opts.image_height/2), text=r.traditional, font=font, anchor="mm", align="center")
                # print(textbox_val)
                file_name = f"hanzi_{r.codepoint}_{font_name}_simp.png"
                draw2.text(
                    (opts.image_width/2, opts.image_height/2), text=r.simplified, font=font, fill="black", anchor="mm", align="center"
                )
                img2.save(
                    os.path.join(
                        root_,
                        opts.data_folder,
                        opts.save_location,
                        file_name,
                    )
                )
                manifest_df.loc[len(manifest_df)] = [file_name, r.simplified, font_name]
                num_img += 1
                
            # If they're the same it doesn't really matter which we save, but we'll save the traditional since that's our priority
            else:
                img = Image.new("RGB", (opts.image_width, opts.image_height), "white")
                draw = ImageDraw.Draw(img)
                # textbox_val = draw.textbbox((opts.image_width/2, opts.image_height/2), text=r.simplified, font=font, anchor="mm", align="center")
                # print(textbox_val)
                file_name = f"hanzi_{r.codepoint}_{font_name}_both.png"
                draw.text((opts.image_width/2, opts.image_height/2), text=r.simplified, font=font, fill="black", anchor="mm", align="center")
                img.save(
                    os.path.join(
                        root_,
                        opts.data_folder,
                        opts.save_location,
                        file_name,
                    )
                )
                manifest_df.loc[len(manifest_df)] = [file_name, r.simplified, font_name]
                num_img += 1

        # At the end we'll save our manifest df as a csv, this is important since this stores our ys for each X, the X being the image
        if not os.path.exists(os.path.join(root_, opts.data_folder, opts.manifest_location)):
            os.makedirs(os.path.join(root_, opts.data_folder, opts.manifest_location))
        manifest_df.to_csv(os.path.join(root_, opts.data_folder, opts.manifest_location, opts.manifest_name))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_folder",
        type=str,
        default="data/",
        help="Root folder for the data inside the root project directory",
    )

    parser.add_argument(
        "--font_location",
        type=str,
        default="fonts/",
        help="Folder with the fonts to be read",
    )

    parser.add_argument(
        "--hanzi_location",
        type=str,
        default="characters",
        help="Folder with processed hanzi list",
    )

    parser.add_argument(
        "--hanzi_file_name",
        type=str,
        default="characters.csv",
        help="File in which the hanzi list is stored",
    )

    parser.add_argument(
        "--save_location",
        type=str,
        default="character_images/",
        help="Directory in which to save the images with the characters",
    )

    parser.add_argument(
        "--manifest_location",
        type=str,
        default="images_manifest/",
        help="Location in which to save the manifest file for the generated images"
    )

    parser.add_argument(
        "--manifest_name",
        type=str,
        default="manifest.csv",
        help="Name for the manifest file, it will store the image name, character, font, size, etc"
    )

    parser.add_argument(
        "--save_traditional",
        type=utils.str2bool,
        default=False,
        help="Whether or not to generate images for traditional characters alongside the simplified ones",
    )

    parser.add_argument(
        "--image_width", 
        type=int,
        default="300",
        help="Width of the generated image"
    )

    parser.add_argument(
        "--character_size",
        type=int,
        default=250,
        help="Character size, in pixels. You want this to be smaller than the image width and height"
    )

    parser.add_argument(
        "--image_height", 
        type=int,
        default="300",
        help="Height of the generated image"
    )

    parser.add_argument(
        "--delete_previous_images",
        type=utils.str2bool,
        default=True,
        help="If True deletes all previously generated images in the destination folder",
    )

    opts = parser.parse_args()
    if opts.delete_previous_images:
        delete_images(opts)
    write_images(opts)


if __name__ == "__main__":
    main()
